name: flutter_chat_types
description: >
  Utility library for the flutter_chat_ui and flutter_firebase_chat_core libraries
  which contains shared type declarations.
version: 3.4.1
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_types

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
