name: flutter_chat_types
description: >
  Utility library for the flutter_chat_ui and flutter_firebase_chat_core libraries
  which contains shared type declarations.
version: 3.3.0
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_types

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
