name: flutter_chat_types
description: >
  Utility library for the flutter_chat_ui and flutter_firebase_chat_core libraries
  which contains shared type declarations.
version: 2.1.3
homepage: https://flyer.chat

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.2
  meta: ^1.3.0
