name: flutter_chat_types
description: >
  Utility library for the flutter_chat_ui and flutter_firebase_chat_core libraries
  which contains shared type declarations.
version: 2.0.0
homepage: https://github.com/flyerhq/flutter_chat_types

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.3.0
