name: flutter_chat_types
description: >
  Utility library for the flutter_chat_ui and flutter_firebase_chat_core libraries
  which contains shared type declarations.
version: 3.6.1
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_types

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2
